In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import torch.nn as nn

import os
import zipfile
import urllib.request

## downloading data

In [4]:
folder_name = "ml-1m"
zip_path = "ml-1m.zip"
data_url = "http://files.grouplens.org/datasets/movielens/ml-1m.zip"

if not os.path.exists(folder_name):
    print("there is no data. downloading")
    
    urllib.request.urlretrieve(data_url, zip_path)
    
    with zipfile.ZipFile(zip_path, "r") as zip_data:
        zip_data.extractall(".")
        
        os.remove(zip_path)
        print('data is downloaded')
else:
    print('data already exists')

there is no data. downloading
data is downloaded

In [16]:
file_path = 'ml-1m/ratings.dat'
col_names = ['user_id', 'item_id', 'rating', 'timestamp']

df = pd.read_csv(file_path, sep='::', engine='python', names=col_names)
df.head()

   user_id  item_id  rating  timestamp
0        1     1193       5  978300760
1        1      661       3  978302109
2        1      914       3  978301968
3        1     3408       4  978300275
4        1     2355       5  978824291

In [17]:
print(f'interactions quantity: {df.shape}')
print(f'unique users: {len(df['user_id'].unique())}')
print(f'unique items: {len(df['item_id'].unique())}')

interactions quantity: (1000209, 4)
unique users: 6040
unique items: 3706

In [33]:
def rating_quantity(main_data, group_by_col, func_col, func):
    group_df = main_data.groupby(group_by_col).agg(
        quantity=(func_col, func)
    ).reset_index()
    
    group_df = group_df.rename(columns={
        'quantity':f'{func_col}_quantity'
    })
    
    group_df = group_df.sort_values(by=f'{func_col}_quantity', ascending=False)
    
    return group_df

user_rating = rating_quantity(df, 'user_id', 'rating', 'count')
item_rating = rating_quantity(df, 'item_id', 'rating', 'count')

In [34]:
item_rating.head(10)

      item_id  rating_quantity
2651     2858             3428
253       260             2991
1106     1196             2990
1120     1210             2883
466       480             2672
1848     2028             2653
575       589             2649
2374     2571             2590
1178     1270             2583
579       593             2578

In [35]:
user_rating.head(10)

      user_id  rating_quantity
4168     4169             2314
1679     1680             1850
4276     4277             1743
1940     1941             1595
1180     1181             1521
888       889             1518
3617     3618             1344
2062     2063             1323
1149     1150             1302
1014     1015             1286